# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PP\tempcalc\test1.ui',
# licensing of 'D:\PP\tempcalc\test1.ui' applies.
#
# Created: Wed Feb 12 20:01:42 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 466)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 541, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 471, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_pw2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw2.setObjectName("lineEdit_pw2")
        self.gridLayout_2.addWidget(self.lineEdit_pw2, 2, 2, 1, 1)
        self.label_pw2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw2.setObjectName("label_pw2")
        self.gridLayout_2.addWidget(self.label_pw2, 2, 0, 1, 2)
        self.label_pw3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw3.setObjectName("label_pw3")
        self.gridLayout_2.addWidget(self.label_pw3, 3, 0, 1, 2)
        self.comboBox_14 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_14, 4, 3, 1, 2)
        self.lineEdit_pw4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw4.setObjectName("lineEdit_pw4")
        self.gridLayout_2.addWidget(self.lineEdit_pw4, 4, 2, 1, 1)
        self.label_pw5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw5.setObjectName("label_pw5")
        self.gridLayout_2.addWidget(self.label_pw5, 5, 0, 1, 2)
        self.lineEdit_pw3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw3.setObjectName("lineEdit_pw3")
        self.gridLayout_2.addWidget(self.lineEdit_pw3, 3, 2, 1, 1)
        self.lineEdit_pw1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw1.setObjectName("lineEdit_pw1")
        self.gridLayout_2.addWidget(self.lineEdit_pw1, 1, 2, 1, 1)
        self.label_pw4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw4.setObjectName("label_pw4")
        self.gridLayout_2.addWidget(self.label_pw4, 4, 0, 1, 2)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_8, 3, 3, 1, 2)
        self.label_pw = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_pw.setFont(font)
        self.label_pw.setObjectName("label_pw")
        self.gridLayout_2.addWidget(self.label_pw, 0, 0, 1, 5)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_10, 1, 3, 1, 2)
        self.label_pw7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw7.setObjectName("label_pw7")
        self.gridLayout_2.addWidget(self.label_pw7, 7, 0, 1, 2)
        self.lineEdit_pw5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw5.setObjectName("lineEdit_pw5")
        self.gridLayout_2.addWidget(self.lineEdit_pw5, 5, 2, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_13, 7, 3, 1, 2)
        self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_11, 5, 3, 1, 2)
        self.lineEdit_pw7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw7.setObjectName("lineEdit_pw7")
        self.gridLayout_2.addWidget(self.lineEdit_pw7, 7, 2, 1, 1)
        self.label_pw1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw1.setObjectName("label_pw1")
        self.gridLayout_2.addWidget(self.label_pw1, 1, 0, 1, 2)
        self.lineEdit_pw9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw9.setObjectName("lineEdit_pw9")
        self.gridLayout_2.addWidget(self.lineEdit_pw9, 9, 2, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_9, 6, 3, 1, 2)
        self.lineEdit_pw6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw6.setObjectName("lineEdit_pw6")
        self.gridLayout_2.addWidget(self.lineEdit_pw6, 6, 2, 1, 1)
        self.lineEdit_pw8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_pw8.setObjectName("lineEdit_pw8")
        self.gridLayout_2.addWidget(self.lineEdit_pw8, 8, 2, 1, 1)
        self.label_pw6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw6.setObjectName("label_pw6")
        self.gridLayout_2.addWidget(self.label_pw6, 6, 0, 1, 2)
        self.comboBox_12 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_12, 2, 3, 1, 2)
        self.label_pw8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw8.setObjectName("label_pw8")
        self.gridLayout_2.addWidget(self.label_pw8, 8, 0, 1, 2)
        self.label_pw9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_pw9.setObjectName("label_pw9")
        self.gridLayout_2.addWidget(self.label_pw9, 9, 0, 1, 2)
        self.comboBox_23 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_23, 8, 3, 1, 2)
        self.comboBox_22 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_22, 9, 3, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 471, 271))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_prj3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj3.setObjectName("lineEdit_prj3")
        self.gridLayout.addWidget(self.lineEdit_prj3, 3, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 5, 3, 1, 2)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 4, 3, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 3, 3, 1, 2)
        self.label_prj6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj6.setObjectName("label_prj6")
        self.gridLayout.addWidget(self.label_prj6, 6, 0, 1, 2)
        self.label_prj4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj4.setObjectName("label_prj4")
        self.gridLayout.addWidget(self.label_prj4, 4, 0, 1, 2)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 6, 3, 1, 2)
        self.label_prj = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_prj.setFont(font)
        self.label_prj.setObjectName("label_prj")
        self.gridLayout.addWidget(self.label_prj, 0, 0, 1, 5)
        self.label_prj2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj2.setObjectName("label_prj2")
        self.gridLayout.addWidget(self.label_prj2, 2, 0, 1, 2)
        self.lineEdit_prj2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj2.setObjectName("lineEdit_prj2")
        self.gridLayout.addWidget(self.lineEdit_prj2, 2, 2, 1, 1)
        self.lineEdit_prj6 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj6.setObjectName("lineEdit_prj6")
        self.gridLayout.addWidget(self.lineEdit_prj6, 6, 2, 1, 1)
        self.label_prj5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj5.setObjectName("label_prj5")
        self.gridLayout.addWidget(self.label_prj5, 5, 0, 1, 2)
        self.lineEdit_prj4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj4.setObjectName("lineEdit_prj4")
        self.gridLayout.addWidget(self.lineEdit_prj4, 4, 2, 1, 1)
        self.lineEdit_prj5 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj5.setObjectName("lineEdit_prj5")
        self.gridLayout.addWidget(self.lineEdit_prj5, 5, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 3, 1, 2)
        self.label_prj3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj3.setObjectName("label_prj3")
        self.gridLayout.addWidget(self.label_prj3, 3, 0, 1, 2)
        self.lineEdit_prj1 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_prj1.setObjectName("lineEdit_prj1")
        self.gridLayout.addWidget(self.lineEdit_prj1, 1, 2, 1, 1)
        self.label_prj1 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_prj1.setObjectName("label_prj1")
        self.gridLayout.addWidget(self.label_prj1, 1, 0, 1, 2)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 1, 3, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 471, 271))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_pp5 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_pp5.setObjectName("lineEdit_pp5")
        self.gridLayout_3.addWidget(self.lineEdit_pp5, 5, 2, 1, 1)
        self.label_pp2 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp2.setObjectName("label_pp2")
        self.gridLayout_3.addWidget(self.label_pp2, 2, 0, 1, 2)
        self.lineEdit_pp1 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_pp1.setObjectName("lineEdit_pp1")
        self.gridLayout_3.addWidget(self.lineEdit_pp1, 1, 2, 1, 1)
        self.comboBox_19 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_19, 2, 3, 1, 2)
        self.lineEdit_pp4 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_pp4.setObjectName("lineEdit_pp4")
        self.gridLayout_3.addWidget(self.lineEdit_pp4, 4, 2, 1, 1)
        self.label_pp1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp1.setObjectName("label_pp1")
        self.gridLayout_3.addWidget(self.label_pp1, 1, 0, 1, 2)
        self.label_pp4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp4.setObjectName("label_pp4")
        self.gridLayout_3.addWidget(self.label_pp4, 4, 0, 1, 2)
        self.label_pp5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp5.setObjectName("label_pp5")
        self.gridLayout_3.addWidget(self.label_pp5, 5, 0, 1, 2)
        self.comboBox_21 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_21, 4, 3, 1, 2)
        self.comboBox_18 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_18, 5, 3, 1, 2)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_7, 1, 3, 1, 2)
        self.label_pp3 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp3.setObjectName("label_pp3")
        self.gridLayout_3.addWidget(self.label_pp3, 3, 0, 1, 2)
        self.comboBox_15 = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_15, 3, 3, 1, 2)
        self.label_pp = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_pp.setFont(font)
        self.label_pp.setObjectName("label_pp")
        self.gridLayout_3.addWidget(self.label_pp, 0, 0, 1, 5)
        self.lineEdit_pp3 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_pp3.setObjectName("lineEdit_pp3")
        self.gridLayout_3.addWidget(self.lineEdit_pp3, 3, 2, 1, 1)
        self.lineEdit_pp2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_pp2.setObjectName("lineEdit_pp2")
        self.gridLayout_3.addWidget(self.lineEdit_pp2, 2, 2, 1, 1)
        self.label_pp6 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_pp6.setText("")
        self.label_pp6.setObjectName("label_pp6")
        self.gridLayout_3.addWidget(self.label_pp6, 6, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_graf = QtWidgets.QLabel(self.tab_4)
        self.label_graf.setGeometry(QtCore.QRect(280, 110, 35, 10))
        self.label_graf.setObjectName("label_graf")
        self.pushButton_graf = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_graf.setGeometry(QtCore.QRect(40, 200, 56, 17))
        self.pushButton_graf.setObjectName("pushButton_graf")
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 380, 181, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 380, 141, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_pw2.setText(QtWidgets.QApplication.translate("MainWindow", "Внешний диаметр НКТ", None, -1))
        self.label_pw3.setText(QtWidgets.QApplication.translate("MainWindow", "Теплопроводность НКТ", None, -1))
        self.comboBox_14.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_14.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_14.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_14.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_pw5.setText(QtWidgets.QApplication.translate("MainWindow", "Внешний диаметр колонны", None, -1))
        self.label_pw4.setText(QtWidgets.QApplication.translate("MainWindow", "Внутренний диаметр колонны", None, -1))
        self.comboBox_8.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_8.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.label_pw.setText(QtWidgets.QApplication.translate("MainWindow", "Параметры скважины", None, -1))
        self.comboBox_10.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_10.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_10.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_10.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_pw7.setText(QtWidgets.QApplication.translate("MainWindow", "Диаметр скважины", None, -1))
        self.comboBox_13.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_13.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_13.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_13.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.comboBox_11.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_11.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_11.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_11.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_pw1.setText(QtWidgets.QApplication.translate("MainWindow", "Внутренний диаметр НКТ", None, -1))
        self.comboBox_9.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_9.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.label_pw6.setText(QtWidgets.QApplication.translate("MainWindow", "Теплопроводностьо стенки колонны", None, -1))
        self.comboBox_12.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_12.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_12.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_12.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_pw8.setText(QtWidgets.QApplication.translate("MainWindow", "Теплопроводность цемента", None, -1))
        self.label_pw9.setText(QtWidgets.QApplication.translate("MainWindow", "Глубина спуска НКТ", None, -1))
        self.comboBox_23.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_23.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_22.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.comboBox_22.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Tab 1", None, -1))
        self.comboBox_4.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "сПз", None, -1))
        self.comboBox_4.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "сПз", None, -1))
        self.comboBox_3.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_3.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_2.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "кг/м^3", None, -1))
        self.comboBox_2.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "кг/м^3", None, -1))
        self.label_prj6.setText(QtWidgets.QApplication.translate("MainWindow", "Расход (объёмный)", None, -1))
        self.label_prj4.setText(QtWidgets.QApplication.translate("MainWindow", "Теплопроводность", None, -1))
        self.comboBox_5.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "м^3/час", None, -1))
        self.comboBox_5.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "м^3/час", None, -1))
        self.label_prj.setText(QtWidgets.QApplication.translate("MainWindow", "Параметры рабочей жидкости", None, -1))
        self.label_prj2.setText(QtWidgets.QApplication.translate("MainWindow", "Удельная теплоёмкость", None, -1))
        self.label_prj5.setText(QtWidgets.QApplication.translate("MainWindow", "Динамическая вязкость", None, -1))
        self.comboBox.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Дж/(кг*С)", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Дж/(кг*С)", None, -1))
        self.label_prj3.setText(QtWidgets.QApplication.translate("MainWindow", "Плотность", None, -1))
        self.label_prj1.setText(QtWidgets.QApplication.translate("MainWindow", "Температура на поверхности", None, -1))
        self.comboBox_6.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "С", None, -1))
        self.comboBox_6.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "С", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Tab 2", None, -1))
        self.label_pp2.setText(QtWidgets.QApplication.translate("MainWindow", "Теплопроводность породы", None, -1))
        self.comboBox_19.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_19.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_19.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_19.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.label_pp1.setText(QtWidgets.QApplication.translate("MainWindow", "Темп. нейтрального слоя", None, -1))
        self.label_pp4.setText(QtWidgets.QApplication.translate("MainWindow", "Плотность пород", None, -1))
        self.label_pp5.setText(QtWidgets.QApplication.translate("MainWindow", "Геотермический градиент", None, -1))
        self.comboBox_21.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_21.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "мм", None, -1))
        self.comboBox_21.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "см", None, -1))
        self.comboBox_21.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "м", None, -1))
        self.comboBox_18.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "C/м", None, -1))
        self.comboBox_18.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "C/м", None, -1))
        self.comboBox_7.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "С", None, -1))
        self.comboBox_7.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "С", None, -1))
        self.label_pp3.setText(QtWidgets.QApplication.translate("MainWindow", "Теплоёмкость породы", None, -1))
        self.comboBox_15.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.comboBox_15.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Вт/м*С", None, -1))
        self.label_pp.setText(QtWidgets.QApplication.translate("MainWindow", "Параметры породы", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtWidgets.QApplication.translate("MainWindow", "Страница", None, -1))
        self.label_graf.setText(QtWidgets.QApplication.translate("MainWindow", "TextLabel", None, -1))
        self.pushButton_graf.setText(QtWidgets.QApplication.translate("MainWindow", "PushButton", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "Страница", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MainWindow", "Заполнить из файла", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Записать в файл", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

